---
- name: Install pip
  apt:
    pkg: python-pip
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade pip and install docker module
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - docker
    - docker-compose

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_directory }}"
    - "{{ traefik_directory }}/conf.d"
