---
- name: start traefik
  docker_service:
    state: present
    project_src: "{{ traefik_directory }}"

- name: restart traefik
  docker_service:
    state: present
    project_src: "{{ traefik_directory }}"
    restarted: true
